### PR TITLE
Feature/update cake2.0

### LINKED ISSUE #96: Update Cake.Json add-in to target Cake v2.0.0
[Cake 2.0.0](https://cakebuild.net/blog/2021/11/cake-v2.0.0-released) has been released 🎉

### PR DESCRIPTION
**Pull request by twenzel**
- Update reference to Cake 2.0
- Update icon to new addin icon
- Use Ubuntu as build image on Appveyor
Fixes #96, #94, #95, #92, #93

### CODE REVIEW

**Review by augustoproiete — CHANGES_REQUESTED** [review]
LGTM.

Could you add the .NET 6 SDK to https://github.com/cake-contrib/Cake.Json/blob/develop/.github/workflows/codeql-analysis.yml as well to fix the build?

**Comment by nils-a** [comment]
@augustoproiete Cake 2.0.0 internally uses [`Newtonsoft.Json` in version `13.0.1`](https://github.com/cake-build/cake/blob/34f522f17b143af0a5e91564e755bd41635c2809/src/Cake.NuGet/Cake.NuGet.csproj#L27) should we update to the same reference here, when we update to Cake 2.0.0?

**Comment by augustoproiete** [comment]
@nils-a Yes, that's a good idea. @twenzel Want to add this one?

**Review by augustoproiete — APPROVED** [review]
LGTM

**Comment by augustoproiete** [comment]
@twenzel is a machine 🤖

**Review by nils-a — APPROVED** [review]
LGTM!

**Comment by nils-a** [comment]
@twenzel your changes have been merged, thanks for your contribution :+1:

**Pull request merged**
