### PR TITLE
Bump dependencies

### LINKED ISSUE #37: Bump dependencies to reduce Cake warnings

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #37.

Note: also bumped `Newtonsoft.Json` to 11.0.2 to match `Cake` 0.33.0 dependency.

### CODE REVIEW

**Comment by gitfool** [comment]
There are a few related issues and PRs hanging around.

After merging this PR, you should be able to close it along with #15 #21 #29 #33 #34 #35 #36.

**Comment by gep13** [comment]
@gitfool I have rebased and merged this here: https://github.com/cake-contrib/Cake.Json/commit/e3ac17278df2bd52bef4308b480e31b149a4a363

**Comment by gep13** [comment]
@gitfool your changes have been merged, thanks for your contribution 👍

**Comment by gitfool** [comment]
@gep13 are you going to release this or is something else in the way?

**Pull request closed without merging**
