### PR TITLE
Upgrade to Cake 1.0.0

### LINKED ISSUE #49: Compatibility warning when running against Cake v1.0.0
## Expected Behavior

When using Cake.Json in a build script that uses Cake 1.0.0, there should not be any compatibility warnings displayed.

## Current Behavior

Using the latest version (5.2.0) of Cake.Json with Cake 1.0.0 causes a warning message during build:

```
The assembly 'Cake.Json, Version=5.2.0.0, Culture=neutral, PublicKeyToken=null' is referencing an older version of Cake.Core (0.35.0). 
For best compatibility it should target Cake.Core version 1.0.0.
```

## Possible Solution

Update Cake.Json to target Cake 1.0.0.

## Context

This issue has no real impact beyond a mildly annoying warning message, as there do not seem to be any actual compatibility issues.

### PR DESCRIPTION
**Pull request by AdaskoTheBeAsT**
## Description
Upgrade to Cake 1.0.0. Closes #49;

## Related Issue
https://github.com/cake-contrib/Cake.Json/issues/49

## Motivation and Context
Help with upgradig plugins.

## How Has This Been Tested?
Launched all tests on local machine

## Types of changes

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X ] My code follows the code style of this project.
- [X ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X ] All new and existing tests passed.

### CODE REVIEW

**Comment by AdaskoTheBeAsT** [comment]
My bad - I thought that it will be easy :) Please advise

**Comment by nils-a** [comment]
@AdaskoTheBeAsT I have created a PR on this PR. That "should" fix the build which was seemingly broken even before you started.

**Comment by AdaskoTheBeAsT** [comment]
Thanks - close but not yet :)

**Comment by nils-a** [comment]
I /think/ there is a `.\build.ps1 --bootstrap` missing in the `.appveyor.yml`

**Comment by AdaskoTheBeAsT** [comment]
hmm still doesn't work - probably something simple which I do not see 😄

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@AdaskoTheBeAsT I took the liberty of rebasing your PR onto the head of the develop branch, as I was able to get the builds working.

Thank you very much for your help in getting this addin updated!

**Comment by AdaskoTheBeAsT** [comment]
It is amazing to constantly learn even from unperfect pull requests :) thanks for making it work

**Comment by gep13** [comment]
>@AdaskoTheBeAsT said.
thanks for making it work

You are very welcome!

**Pull request merged**
